version: 1
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make provider
builds:
  - binary: pulumi-resource-vercel
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -s
      - -w
      - -X github.com/pulumiverse/pulumi-vercel/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-vercel/
changelog:
  disable: true
release:
  disable: false
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
