name: main

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
  pull_request_target:
  workflow_dispatch:

jobs:
  prerequisites:
    permissions:
      pull-requests: write
    uses: pulumiverse/infra/.github/workflows/provider-prerequisites.yaml@main
    with:
      provider: vercel
      goversion: 1.21
  build:
    needs: prerequisites
    uses: pulumiverse/infra/.github/workflows/provider-build-sdk.yaml@main
    with:
      provider: vercel
      goversion: 1.21
      dotnetversion: 6.0
      nodeversion: 18
      pythonversion: 3.8
